//! Quest Makepad adapter for native Matter animated-surface runtime output.
//!
//! This crate converts replay frames and Matter runtime payloads into bounded
//! app-facing rows and renderer-neutral Optics visuals. It does not own
//! simulation truth, settings resolution, Android property transport, or
//! Makepad backend resources.

mod adf;
mod adf_world;
mod config;
mod constants;
mod error;
mod frame;
mod geometry;
mod gpu_residency;
mod markers;
mod recorded_hand_source;
mod runtime;
mod source;
mod uploads;
mod worker;

pub use adf::{
    QuestMakepadAdfDebugConfig, QuestMakepadAdfDebugError, QuestMakepadAdfDebugFrame,
    QUEST_MAKEPAD_ADF_DEBUG_SCHEMA_ID, QUEST_MAKEPAD_ADF_DEBUG_VISUAL_ID,
};
pub use adf_world::{
    world_adf_debug_batch_from_frame, QuestMakepadWorldAdfDebugBatch,
    QuestMakepadWorldAdfDebugCell, QuestMakepadWorldAdfDebugPlacement,
    QUEST_MAKEPAD_WORLD_ADF_DEBUG_BATCH_SCHEMA_ID,
    QUEST_MAKEPAD_WORLD_ADF_DEBUG_EVEN_SELECTION_POLICY,
    QUEST_MAKEPAD_WORLD_ADF_DEBUG_MARKER_PREFIX, QUEST_MAKEPAD_WORLD_ADF_DEBUG_RENDER_MODE,
};
pub use config::{QuestMakepadMatterParticleForceOracleConfig, QuestMakepadMatterSurfaceConfig};
pub use constants::{
    DEFAULT_MIN_PARTICLE_RADIUS, DEFAULT_PARTICLE_CLOUD_RADIUS_SCALE,
    DEFAULT_PARTICLE_EXECUTION_BATCH_SIZE, DEFAULT_PARTICLE_RADIUS_SCALE,
    DEFAULT_SDF_ADF_DEBUG_UPDATE_INTERVAL_FRAMES, DEFAULT_WORLD_CONTENT_CENTER,
    DEFAULT_WORLD_CONTENT_TARGET_RADIUS, QUEST_MAKEPAD_CENTER_PROJECTED_BILLBOARD_MODE,
    QUEST_MAKEPAD_COLLISION_UPLOAD_SCHEMA_ID, QUEST_MAKEPAD_CONTENT_LOCAL_SPACE,
    QUEST_MAKEPAD_DISTANCE_SLICE_UPLOAD_SCHEMA_ID, QUEST_MAKEPAD_MATTER_SURFACE_MARKER_PREFIX,
    QUEST_MAKEPAD_MATTER_SURFACE_SCHEMA_ID, QUEST_MAKEPAD_PARTICLE_UPLOAD_SCHEMA_ID,
    QUEST_MAKEPAD_START_HEAD_LOCAL_SPACE, QUEST_MAKEPAD_WORLD_PARTICLE_BATCH_SCHEMA_ID,
    QUEST_MAKEPAD_WORLD_PARTICLE_BILLBOARD_ANIMATION_MODE,
    QUEST_MAKEPAD_WORLD_PARTICLE_BILLBOARD_ANIMATION_SOURCE,
    QUEST_MAKEPAD_WORLD_PARTICLE_BILLBOARD_REFERENCE,
    QUEST_MAKEPAD_WORLD_PARTICLE_BILLBOARD_RENDERER_ID,
    QUEST_MAKEPAD_WORLD_PARTICLE_EVEN_SELECTION_POLICY, QUEST_MAKEPAD_WORLD_PARTICLE_MARKER_PREFIX,
};
pub use error::QuestMakepadMatterSurfaceError;
pub use frame::{QuestMakepadMatterSurfaceFrame, QuestMakepadMatterSurfaceStageTimings};
pub use gpu_residency::{
    QuestMakepadForceAuthorityMode, QuestMakepadGpuComputePreflight,
    QuestMakepadGpuComputeResourceKind, QuestMakepadGpuFieldConstructionReceipt,
    QuestMakepadGpuFieldForceProbe, QuestMakepadGpuFieldForceProbeReadback,
    QuestMakepadGpuFieldForceSamplingProbe, QuestMakepadGpuFieldForceSamplingProbeReadback,
    QuestMakepadGpuFieldParticleForceProbe, QuestMakepadGpuFieldParticleForceProbeInput,
    QuestMakepadGpuFieldParticleForceProbeSample, QuestMakepadGpuFieldSamplingProbe,
    QuestMakepadGpuFieldSamplingProbeReadback, QuestMakepadGpuForceAuthorityCandidate,
    QuestMakepadGpuForceAuthorityGate, QuestMakepadGpuForceAuthorityPromotionEvidence,
    QuestMakepadGpuForceAuthorityResidencyHealth, QuestMakepadGpuForceAuthorityResidencyTracker,
    QuestMakepadGpuMeshSdfForceProbeSample, QuestMakepadGpuMeshSdfProbe,
    QuestMakepadGpuMeshSdfProbeGrid, QuestMakepadGpuMeshSdfProbeInput,
    QuestMakepadGpuMeshSdfProbeReadback, QuestMakepadGpuMeshSdfProbeSample,
    QuestMakepadGpuOracleComputeProbe, QuestMakepadGpuOracleComputeProbeReadback,
    QuestMakepadGpuResidencyPayloadKind, QuestMakepadGpuResidencyProof,
    QuestMakepadGpuSkinningMeshProbe, QuestMakepadGpuSkinningMeshProbeInput,
    QuestMakepadGpuSkinningMeshProbeReadback, QuestMakepadGpuSkinningMeshVertex,
    QuestMakepadGpuSkinningProbe, QuestMakepadGpuSkinningProbeInput,
    QuestMakepadGpuSkinningProbeReadback, QuestMakepadGpuSkinningProbeSample,
    QuestMakepadGpuStorageProbe, QuestMakepadGpuStorageProbeReadback,
    QuestMakepadRuntimeForceAuthorityKind, QuestMakepadRuntimeForceAuthoritySelection,
    QUEST_MAKEPAD_ADF_DEBUG_GPU_RESIDENCY_ROW_STRIDE_BYTES,
    QUEST_MAKEPAD_FORCE_AUTHORITY_MODE_GPU_DENSE_SDF_FIELD_PARTICLE_FORCE,
    QUEST_MAKEPAD_FORCE_AUTHORITY_MODE_MATTER_CPU, QUEST_MAKEPAD_FORCE_AUTHORITY_ROLLBACK_POLICY,
    QUEST_MAKEPAD_GPU_COMPUTE_DEFAULT_READBACK_PROBE_COUNT,
    QUEST_MAKEPAD_GPU_COMPUTE_PREFLIGHT_BACKEND_STATUS,
    QUEST_MAKEPAD_GPU_COMPUTE_PREFLIGHT_MARKER_PREFIX,
    QUEST_MAKEPAD_GPU_COMPUTE_PREFLIGHT_MEASUREMENT_SOURCE,
    QUEST_MAKEPAD_GPU_COMPUTE_PREFLIGHT_READBACK_POLICY,
    QUEST_MAKEPAD_GPU_COMPUTE_PREFLIGHT_RESOURCE_PLANE,
    QUEST_MAKEPAD_GPU_COMPUTE_PREFLIGHT_SCHEMA_ID,
    QUEST_MAKEPAD_GPU_FIELD_CONSTRUCTION_RECEIPT_CPU_ORACLE,
    QUEST_MAKEPAD_GPU_FIELD_CONSTRUCTION_RECEIPT_FIELD_KIND,
    QUEST_MAKEPAD_GPU_FIELD_CONSTRUCTION_RECEIPT_MARKER_PREFIX,
    QUEST_MAKEPAD_GPU_FIELD_CONSTRUCTION_RECEIPT_RESOURCE_PLANE,
    QUEST_MAKEPAD_GPU_FIELD_CONSTRUCTION_RECEIPT_SCHEMA_ID,
    QUEST_MAKEPAD_GPU_FIELD_CONSTRUCTION_RECEIPT_SOURCE_KIND,
    QUEST_MAKEPAD_GPU_FIELD_CONSTRUCTION_RECEIPT_VALIDATION_INPUT_SHAPE,
    QUEST_MAKEPAD_GPU_FIELD_FORCE_PROBE_BACKEND, QUEST_MAKEPAD_GPU_FIELD_FORCE_PROBE_MARKER_PREFIX,
    QUEST_MAKEPAD_GPU_FIELD_FORCE_PROBE_MEASUREMENT_SOURCE,
    QUEST_MAKEPAD_GPU_FIELD_FORCE_PROBE_PAYLOAD, QUEST_MAKEPAD_GPU_FIELD_FORCE_PROBE_SCHEMA_ID,
    QUEST_MAKEPAD_GPU_FIELD_FORCE_SAMPLING_PROBE_CPU_ORACLE,
    QUEST_MAKEPAD_GPU_FIELD_FORCE_SAMPLING_PROBE_DEFAULT_TOLERANCE,
    QUEST_MAKEPAD_GPU_FIELD_FORCE_SAMPLING_PROBE_MARKER_PREFIX,
    QUEST_MAKEPAD_GPU_FIELD_FORCE_SAMPLING_PROBE_MEASUREMENT_SOURCE,
    QUEST_MAKEPAD_GPU_FIELD_FORCE_SAMPLING_PROBE_RESOURCE_PLANE,
    QUEST_MAKEPAD_GPU_FIELD_FORCE_SAMPLING_PROBE_SAMPLES,
    QUEST_MAKEPAD_GPU_FIELD_FORCE_SAMPLING_PROBE_SCHEMA_ID,
    QUEST_MAKEPAD_GPU_FIELD_PARTICLE_FORCE_PROBE_CPU_ORACLE,
    QUEST_MAKEPAD_GPU_FIELD_PARTICLE_FORCE_PROBE_DEFAULT_TOLERANCE,
    QUEST_MAKEPAD_GPU_FIELD_PARTICLE_FORCE_PROBE_MARKER_PREFIX,
    QUEST_MAKEPAD_GPU_FIELD_PARTICLE_FORCE_PROBE_MEASUREMENT_SOURCE,
    QUEST_MAKEPAD_GPU_FIELD_PARTICLE_FORCE_PROBE_RESOURCE_PLANE,
    QUEST_MAKEPAD_GPU_FIELD_PARTICLE_FORCE_PROBE_SAMPLES,
    QUEST_MAKEPAD_GPU_FIELD_PARTICLE_FORCE_PROBE_SCHEMA_ID,
    QUEST_MAKEPAD_GPU_FIELD_SAMPLING_PROBE_CPU_ORACLE,
    QUEST_MAKEPAD_GPU_FIELD_SAMPLING_PROBE_DEFAULT_TOLERANCE,
    QUEST_MAKEPAD_GPU_FIELD_SAMPLING_PROBE_MARKER_PREFIX,
    QUEST_MAKEPAD_GPU_FIELD_SAMPLING_PROBE_MEASUREMENT_SOURCE,
    QUEST_MAKEPAD_GPU_FIELD_SAMPLING_PROBE_RESOURCE_PLANE,
    QUEST_MAKEPAD_GPU_FIELD_SAMPLING_PROBE_SAMPLES,
    QUEST_MAKEPAD_GPU_FIELD_SAMPLING_PROBE_SCHEMA_ID,
    QUEST_MAKEPAD_GPU_FORCE_AUTHORITY_CANDIDATE_ACTIVE_AUTHORITY_SOURCE,
    QUEST_MAKEPAD_GPU_FORCE_AUTHORITY_CANDIDATE_KIND,
    QUEST_MAKEPAD_GPU_FORCE_AUTHORITY_CANDIDATE_MARKER_PREFIX,
    QUEST_MAKEPAD_GPU_FORCE_AUTHORITY_CANDIDATE_SCHEMA_ID,
    QUEST_MAKEPAD_GPU_FORCE_AUTHORITY_GATE_KIND,
    QUEST_MAKEPAD_GPU_FORCE_AUTHORITY_GATE_MARKER_PREFIX,
    QUEST_MAKEPAD_GPU_FORCE_AUTHORITY_GATE_POLICY,
    QUEST_MAKEPAD_GPU_FORCE_AUTHORITY_GATE_SCHEMA_ID,
    QUEST_MAKEPAD_GPU_FORCE_AUTHORITY_RESIDENCY_KIND,
    QUEST_MAKEPAD_GPU_FORCE_AUTHORITY_RESIDENCY_MARKER_PREFIX,
    QUEST_MAKEPAD_GPU_FORCE_AUTHORITY_RESIDENCY_REQUIRED_PROOFS,
    QUEST_MAKEPAD_GPU_FORCE_AUTHORITY_RESIDENCY_SCHEMA_ID,
    QUEST_MAKEPAD_GPU_FORCE_AUTHORITY_RESIDENCY_TRACKER_SOURCE,
    QUEST_MAKEPAD_GPU_MESH_SDF_FORCE_SAMPLE_PROBE_SAMPLES,
    QUEST_MAKEPAD_GPU_MESH_SDF_PROBE_BACKEND, QUEST_MAKEPAD_GPU_MESH_SDF_PROBE_DEFAULT_TOLERANCE,
    QUEST_MAKEPAD_GPU_MESH_SDF_PROBE_MARKER_PREFIX, QUEST_MAKEPAD_GPU_MESH_SDF_PROBE_MAX_VOXELS,
    QUEST_MAKEPAD_GPU_MESH_SDF_PROBE_MEASUREMENT_SOURCE, QUEST_MAKEPAD_GPU_MESH_SDF_PROBE_PAYLOAD,
    QUEST_MAKEPAD_GPU_MESH_SDF_PROBE_SAMPLES, QUEST_MAKEPAD_GPU_MESH_SDF_PROBE_SCHEMA_ID,
    QUEST_MAKEPAD_GPU_ORACLE_COMPUTE_PROBE_BACKEND,
    QUEST_MAKEPAD_GPU_ORACLE_COMPUTE_PROBE_MARKER_PREFIX,
    QUEST_MAKEPAD_GPU_ORACLE_COMPUTE_PROBE_MEASUREMENT_SOURCE,
    QUEST_MAKEPAD_GPU_ORACLE_COMPUTE_PROBE_PAYLOAD,
    QUEST_MAKEPAD_GPU_ORACLE_COMPUTE_PROBE_RESOURCE_PLANE,
    QUEST_MAKEPAD_GPU_ORACLE_COMPUTE_PROBE_SCHEMA_ID, QUEST_MAKEPAD_GPU_ORACLE_COMPUTE_PROBE_WORDS,
    QUEST_MAKEPAD_GPU_RESIDENCY_BACKEND_MAKEPAD_INSTANCED_DRAW,
    QUEST_MAKEPAD_GPU_RESIDENCY_MARKER_PREFIX, QUEST_MAKEPAD_GPU_RESIDENCY_MEASUREMENT_SOURCE,
    QUEST_MAKEPAD_GPU_RESIDENCY_PROOF_SCHEMA_ID, QUEST_MAKEPAD_GPU_RESIDENCY_RESOURCE_PLANE,
    QUEST_MAKEPAD_GPU_SKINNING_MESH_PROBE_BACKEND,
    QUEST_MAKEPAD_GPU_SKINNING_MESH_PROBE_DEFAULT_TOLERANCE,
    QUEST_MAKEPAD_GPU_SKINNING_MESH_PROBE_MARKER_PREFIX,
    QUEST_MAKEPAD_GPU_SKINNING_MESH_PROBE_MEASUREMENT_SOURCE,
    QUEST_MAKEPAD_GPU_SKINNING_MESH_PROBE_PAYLOAD, QUEST_MAKEPAD_GPU_SKINNING_MESH_PROBE_SAMPLES,
    QUEST_MAKEPAD_GPU_SKINNING_MESH_PROBE_SCHEMA_ID, QUEST_MAKEPAD_GPU_SKINNING_PROBE_BACKEND,
    QUEST_MAKEPAD_GPU_SKINNING_PROBE_DEFAULT_TOLERANCE,
    QUEST_MAKEPAD_GPU_SKINNING_PROBE_MARKER_PREFIX,
    QUEST_MAKEPAD_GPU_SKINNING_PROBE_MEASUREMENT_SOURCE, QUEST_MAKEPAD_GPU_SKINNING_PROBE_PAYLOAD,
    QUEST_MAKEPAD_GPU_SKINNING_PROBE_SAMPLES, QUEST_MAKEPAD_GPU_SKINNING_PROBE_SCHEMA_ID,
    QUEST_MAKEPAD_GPU_STORAGE_PROBE_BACKEND, QUEST_MAKEPAD_GPU_STORAGE_PROBE_DEFAULT_BYTES,
    QUEST_MAKEPAD_GPU_STORAGE_PROBE_DEFAULT_PATTERN, QUEST_MAKEPAD_GPU_STORAGE_PROBE_MARKER_PREFIX,
    QUEST_MAKEPAD_GPU_STORAGE_PROBE_MEASUREMENT_SOURCE,
    QUEST_MAKEPAD_GPU_STORAGE_PROBE_RESOURCE_PLANE, QUEST_MAKEPAD_GPU_STORAGE_PROBE_SCHEMA_ID,
    QUEST_MAKEPAD_PARTICLE_GPU_RESIDENCY_ROW_STRIDE_BYTES,
};
pub use recorded_hand_source::{
    QuestMakepadRecordedHandSourceFrameBuilder, QuestMakepadRecordedHandSourceFrameOptions,
};
pub use runtime::QuestMakepadMatterSurfaceRuntime;
pub use rusty_matter_surface_runtime::{
    MatterSurfaceContactProbe, MatterSurfaceParticleDistanceRefreshPolicy,
    MatterSurfaceParticleForceRefresh, MatterSurfaceParticleForceSource,
    MatterSurfaceParticleForceSourceStatus, ParticleExecutionBackend,
};
pub use source::{QuestMakepadMatterSurfaceProviderShape, QuestMakepadMatterSurfaceSourceFrame};
pub use uploads::{
    world_particle_batch_from_upload, QuestMakepadCollisionRow, QuestMakepadCollisionUpload,
    QuestMakepadDistanceSliceRow, QuestMakepadDistanceSliceUpload, QuestMakepadParticleRow,
    QuestMakepadParticleUpload, QuestMakepadWorldParticleBatch, QuestMakepadWorldParticleInstance,
    QuestMakepadWorldParticlePlacement,
};
pub use worker::{
    QuestMakepadMatterSurfaceWorker, QuestMakepadMatterSurfaceWorkerError,
    QuestMakepadMatterSurfaceWorkerFrame, QuestMakepadMatterSurfaceWorkerOutput,
    QuestMakepadMatterSurfaceWorkerStats, QUEST_MAKEPAD_MATTER_SURFACE_WORKER_MARKER_PREFIX,
    QUEST_MAKEPAD_MATTER_SURFACE_WORKER_SCHEMA_ID,
};

pub(crate) use geometry::{bounds_max_half_extent, bounds_radius, midpoint, vec3_length};
pub(crate) use markers::{sanitize_marker_value, vec3_marker_token};

#[cfg(test)]
mod tests;
